### ISSUE TITLE
Handle endianness for non-native integers

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#123]
To test in the CI, perhaps we could easily build a cross-compiler using one of these tools:

 * https://crosstool-ng.github.io/
 * https://www.embtoolkit.org/
 * https://gist.github.com/preshing/41d5c7248dea16238b60

**Comment by antoyo** [comment]
cc @glaubitz You probably want to watch this issue since you're interested in m68k, which is Big Endian.

**Comment by glaubitz** [comment]
> cc @glaubitz You probably want to watch this issue since you're interested in m68k, which is Big Endian.

Thanks for the heads-up! Much appreciated!

**Comment by antoyo** [comment]
@glaubitz : A good test you might want to do would be to cross-compile the tests of libcore to m68k and see if it works. I couldn't do it when I tested on m68k because there was no support for it in libc back then.

That might show some other things that need to be fixed.

**Comment by glaubitz** [comment]
> @glaubitz : A good test you might want to do would be to cross-compile the tests of libcore to m68k and see if it works.

OK, but first I need to figure out how to build a cross-compiler using the GCC backend in the first place. I haven't tried your guide yet.

> I couldn't do it when I tested on m68k because there was no support for it in libc back then.

m68k support in `libc` is complete now, but the `rustc` source tree has not updated to the latest version of `libc` due to a Illumos-related change breaking the CI (it's being worked on).

I guess I can start adding support for alpha, hppa, ia64 and sh to `libc` as well.

> That might show some other things that need to be fixed.

OK.

**Comment by antoyo** [comment]
@glaubitz: I created this [repo](https://github.com/cross-cg-gcc-tools/cross-gcc) that builds a cross-compiler for m68k for the CI.
It currently requires the git version of [crosstool-ng](https://github.com/crosstool-ng/crosstool-ng).

[There's upcomming support for m68k in the CI!](https://github.com/rust-lang/rustc_codegen_gcc/pull/346)
I still need to write some instructions about this, but it should now be much simpler to test cross-compiling with rustc_codegen_gcc.

**Comment by glaubitz** [comment]
> @glaubitz: I created this [repo](https://github.com/cross-cg-gcc-tools/cross-gcc) that builds a cross-compiler for m68k for the CI. It currently requires the git version of [crosstool-ng](https://github.com/crosstool-ng/crosstool-ng).
> 
> [There's upcomming support for m68k in the CI!](https://github.com/rust-lang/rustc_codegen_gcc/pull/346) I still need to write some instructions about this, but it should now be much simpler to test cross-compiling with rustc_codegen_gcc.

Thanks. Since my employer will allow me to work on whatever FOSS project I want for a week in the second week of November, I now have a project for that week. ;)

**Comment by antoyo** [comment]
Nice. I added the instructions to build a gcc cross-compiler [here](https://github.com/cross-cg-gcc-tools/cross-gcc).
The rustc_codegen_gcc CI for m68k is merged.

@glaubitz: Do you want that I test building a cross-compiler with `crosstool-ng` for other architectures?
I'm asking because it required a change to this tool in order to be able to build a cross-compiler for m68k using `glibc`.
So, I could see if stuff is missing for those other architectures and hopefully have that fixed before your tests.

**Comment by glaubitz** [comment]
I would like to enable this backend for as many architectures in Debian without Rust support as possible.

The next candidate for this would be hppa for which @hdeller has already started working on support for `rust-libc`.

**Comment by antoyo** [comment]
Do you use the glibc as well for HPPA or do you use another c library?

**Comment by hdeller** [comment]
Yes, glibc.

**Comment by antoyo** [comment]
@glaubitz: I forgot to mention: GCC uses a different ABI for m68k than the one currently used in Rust, so you might need to add a new Rust target using the GCC ABI. I'm not too familiar with all this, so I'm not sure what would be needed.

**Comment by glaubitz** [comment]
> @glaubitz: Do you know which programs you plan to compile for Debian? I could try to compile them and fix bugs I find.

I am currently most interested in `cargo` and `librsvg`.

**Comment by antoyo** [comment]
So, I tried compiling those projects and I'm in the process of fixing some issues. This should be all working for x86 when this [PR](https://github.com/rust-lang/rustc_codegen_gcc/pull/368) is merged.

When trying to compile `cargo` for m68k, I get the following error:
```
error[E0432]: unresolved import `crate::general`
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/linux-raw-sys-0.4.10/src/lib.rs:139:16
    |
139 |     use crate::general::__kernel_fd_set;
    |                ^^^^^^^ could not find `general` in the crate root
```
so it looks like at least one crate will need to be updated.

And for librsvg, I got this error:
```
  thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yeslogic-fontconfig-sys-4.0.1/build.rs:8:48:
  called `Result::unwrap()` on an `Err` value: "pkg-config has not been configured to support cross-compilation.\n\nInstall a sysroot for the target platform and configure it via\nPKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a\ncross-compiling wrapper for pkg-config and set it via\nPKG_CONFIG environment variable."
```
So, I assume you'll have to setup `pkg-config` properly.

**Comment by antoyo** [comment]
@glaubitz: Have you got the chance to try compiling those projects for m68k?

**Comment by glaubitz** [comment]
> @glaubitz: Have you got the chance to try compiling those projects for m68k?

Unfortunately not. I have been very busy with fixing bugs on SuperH and SPARC.

I hope to get around working on m68k again during the holidays. We're planning to switch the default alignment on m68k from 16 to 32 bits which should alleviate many portability problems.

**Comment by glaubitz** [comment]
@antoyo Do you have a guide on how to get started adding a new architecture to `rustc` using `rustc_codegen_gcc`?

I have heard from people in the Dreamcast community that they had success with `sh-elf` using `rustc_codegen_gcc`, so I would like to add `sh4-unknown-linux-gnu` using this backend.

**Comment by antoyo** [comment]
@glaubitz: Let's continue the discussion [here](https://github.com/rust-lang/rustc_codegen_gcc/issues/49#issuecomment-1949347142) instead.
