### ISSUE TITLE
Support -Ctarget-feature and target spec target_feature list

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustc_codegen_gcc#206]
This is necessary for compiling rust-for-linux with cg_gcc.

**Comment by bjorn3** [comment]
When trying to disable SSE using `-Clink-arg="-mno-sse -msoft-float"` I get `libgccjit.so: error: SSE register return with SSE disabled` by the way.

**Comment by antoyo** [comment]
Apparently, there's some CPU feature detection in the D frontend in GCC, so that could be useful as an inspiration for libgccjit.

@philberty also mentioned working on a way to share code across GCC frontends which would also be useful. Did you posted a patch for that somewhere?

**Comment by philberty** [comment]
@antoyo My initial patches for this were here:

https://gcc.gnu.org/pipermail/gcc-patches/2022-July/598929.html
https://gcc.gnu.org/pipermail/gcc-patches/2022-July/598928.html

These were kind of pushed back against for being too complex. These patches were pretty much a copy paste for was done in the D front-end.

I spent a lot of time talking to Ian from the D front-end about this issue and he has a new simpler approach let me CC you into an email with him It would be ideal if we could do this once for the rust and jit front-end's :).
