### ISSUE TITLE
Rustup distribution

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#222]
We probably could do it already if we build with the LLVM codegen the parts of the bootstrap that can't be built yet with cg_gcc.

**Comment by bjorn3** [comment]
For reference this is what cg_clif would need to be distributed with rustup: https://github.com/rust-lang/rust/pull/81746 Should be similar for cg_gcc.

**Comment by GuillaumeGomez** [comment]
Closing in favor of #465.
