### ISSUE TITLE
Remove passing tests from failing-ui-tests12.txt

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#251]
If we check at the [CI for failures](https://github.com/rust-lang/rustc_codegen_gcc/actions/runs/8267543813#summary-22618213855), we see a number of tests that pass.

The idea is to get that number close to 0 because we only want to have the failed tests in this CI.

To do so, we need to remove the passing tests from [this file](https://github.com/rust-lang/rustc_codegen_gcc/blob/master/tests/failing-ui-tests.txt) and [this file](https://github.com/rust-lang/rustc_codegen_gcc/blob/master/tests/failing-ui-tests12.txt).

**Comment by mubarak23** [comment]
@antoyo can you add this description to this Issue

**Comment by mubarak23** [comment]
@antoyo what am seeing here is the number of test that pass, where can i see the actual list of test that pass, this way i can identity them from either of the two list and remove them.

**Comment by antoyo** [comment]
Done.

**Comment by mubarak23** [comment]
@antoyo here is the [PR Link](https://github.com/antoyo/rustc_codegen_gcc/pull/4)

**Comment by mubarak23** [comment]
Sorry, i close the other PR by mistake : NEW [PR LINK](https://github.com/antoyo/rustc_codegen_gcc/pull/5)

**Comment by antoyo** [comment]
Done in https://github.com/antoyo/rustc_codegen_gcc/pull/5.
