### ISSUE TITLE
Stop depending on compiler-rt

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#258]
To make 128-bit integers work on `#[no_core]`.

**Comment by bjorn3** [comment]
For things like 128bit compares this is easy. On at least 64bit LLVM, GCC and Cranelift all don't need them. For some operations like 128bit division the code sequence is long and non-trivial. All existing rustc backends need libgcc/compiler-rt/compiler-builtins there. Including cg_clif from which mini_core_hello_world was copied. Cg_clif puts all 128bit int tests in std_example instead for this reason.

**Comment by antoyo** [comment]
Are you saying they depend on [`compiler-builtins`](https://github.com/rust-lang/compiler-builtins) or [LLVM's `compiler-rt`](https://github.com/llvm-mirror/compiler-rt/tree/master/lib/builtins)?

**Comment by bjorn3** [comment]
libgcc, compiler-rt and compiler-builtins for the most part provide the same interfaces. At least as far as LLVM is concerned they can be used interchangably. It is possible that GCC depends on some things not provided by compiler-rt and compiler-builtins, but in that case it should be easy enough to add it to compiler-builtins.

**Comment by antoyo** [comment]
Ok, I was only talking about removing the dependency on LLVM's compiler-rt. If I understand your comment properly, that should be possible, right?

**Comment by bjorn3** [comment]
You need one of libgcc, compiler-rt and compiler-builtins. For mini_core_hello_world you have none. If you move the i128 tests to std_example it should already work just fine.
