### ISSUE TITLE
Add #[must_use] to libgccjit Context::new_call

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#358]
The result of of the method [`Context::new_call()`](https://github.com/rust-lang/gccjit.rs/blob/9f8f67edc006d543b17529a001803ffece48349e/src/context.rs#L693) must always be used, either as part of another expression, or through [`Block::add_eval()`](https://github.com/rust-lang/gccjit.rs/blob/9f8f67edc006d543b17529a001803ffece48349e/src/block.rs#L96) if the call is done for its side effects.

As such, adding the attribute `#[must_use]` attribute will allow seeing where we forget to use the call.

**Comment by mubarak23** [comment]
@antoyo can you add more description to this issue, i will like to pick it and work on it

**Comment by antoyo** [comment]
@mubarak23: I edited the description to add details. Feel free to ask questions if you need more details.

**Comment by mubarak23** [comment]
So Adding the #[must_use] attribute to new_call() would help in catching situations @antoyo

**Comment by mubarak23** [comment]
@antoyo assign this issue to me, let me work on it.

**Comment by antoyo** [comment]
Done. Feel free to ask any questions.

**Comment by mubarak23** [comment]
@antoyo this is the [PR Link](https://github.com/antoyo/rustc_codegen_gcc/pull/3), kindly review, let me know where i can improve or make necessary changes

**Comment by antoyo** [comment]
Done in https://github.com/rust-lang/gccjit.rs/pull/30.
