### ISSUE TITLE
CI: move away from actions-rs

### ISSUE THREAD

**Issue by sadlerap** [rust-lang/rustc_codegen_gcc#381]
As of October 13th, 2023, most of the actions in `actions-rs` have been archived.  Even before then, some actions haven't seen an update in quite a long time (for instance, [`cargo`](https://github.com/actions-rs/cargo) hasn't received any updates since July 2021).

This might be a problem soon, since [github is deprecating support for actions running on node12](https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/) and forcing them to use node16 runners.  Since these are unmaintained, there's a possibility these actions could break without any possibility of fixes landing upstream.

It might be a good idea to find an alternative, though I'm not entirely sure what alternatives to these actions are available.  Does the `cargo` that comes built into the ubuntu image runners support picking up the `rust-toolchain` file as a version override?  If so, that might be an option.

**Comment by madsmtm** [comment]
There is https://github.com/dtolnay/rust-toolchain, which seems to be what a lot of people are gravitating towards
