### ISSUE TITLE
Add test of `./y.sh cargo` in the CI

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#400]
Run `./y.sh cargo build` to compile a project with rustc_codegen_gcc (`y.sh` being the [`build_system`](https://github.com/rust-lang/rustc_codegen_gcc/tree/master/build_system)) to make sure we never break this command.

**Comment by lordshashank** [comment]
@antoyo can You add description to this issue?

**Comment by antoyo** [comment]
@lordshashank: Done. Feel free to ask questions if you need more details.

**Comment by lordshashank** [comment]
@antoyo raised a PR resolving this [here](https://github.com/antoyo/rustc_codegen_gcc/pull/6) . Please review and let me know if something esle is to be done.
