### ISSUE TITLE
Get rid of the file gcc_path?

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#418]
Perhaps we could check if `libgccjit.so` is on the system and alert the user if it cannot be found.

**Comment by YakoYakoYokuYoku** [comment]
We'll have to study the case of having multiple libgccjit, each one targeting a different architecture.

**Comment by GuillaumeGomez** [comment]
This file doesn't exist anymore since we now have the `config.toml` file. Closing.
