### ISSUE TITLE
Give a better description for the commands in the usage of the build system script

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#433]

**Comment by g4titan** [comment]
hello @antoyo, i would love to contribute to this

**Comment by antoyo** [comment]
Thanks. Feel free to ask questions if you need help.

**Comment by g4titan** [comment]
okay, sure

**Comment by g4titan** [comment]
hello @antoyo, assign this task to me

**Comment by g4titan** [comment]
which of the build script are you referring to tho?

**Comment by antoyo** [comment]
The one in [this directory](https://github.com/rust-lang/rustc_codegen_gcc/tree/master/build_system).

The description of the commands are [there](https://github.com/rust-lang/rustc_codegen_gcc/blob/master/build_system/src/main.rs#L26).

**Comment by g4titan** [comment]
hey @antoyo i just committed, please check

**Comment by antoyo** [comment]
> hey @antoyo i just committed, please check

@g4titan: Please do not ping me as I get a notification from GitHub so I already know you pushed your changes :) .
I'll review them when I have time (still work hours here for me).

**Comment by g4titanx** [comment]
hello @antoyo, i dont know y my github acct got flagged, but I have written several support tickets to github and I didn't get a reply, so I created a new github
I would love to work on this issue again

**Comment by antoyo** [comment]
Good, I assigned you this issue.
Thanks!

**Comment by g4titanx** [comment]
great! thanks

**Comment by g4titanx** [comment]
hello @antoyo, you can close this issue now I guess

**Comment by antoyo** [comment]
Done in #490.

Thanks for your contribution!
