### ISSUE TITLE
Enable Rustfmt & Clippy for cg_gcc

### ISSUE THREAD

**Issue by tempdragon** [rust-lang/rustc_codegen_gcc#457]
It takes a long time to manually adjust the code format and style, so I advice to enable the Rustfmt for this project to avoid potential bad styling.
As for clippy, it may be a good idea to reduce the poorly behaved code in Rust to improve code quality. 
```[tasklist]
### Tasks
- [x] Modify the `.rustfmt.toml` and Update the Format with it
- [x] Clean Up the Errors as Is Warned by Clippy
```

**Comment by tempdragon** [comment]
What about using your rustfmt?(Since you contribute the most code). 
It seems that you can simply add your `rustfmt.toml` there? Or maybe I can upload my but it will just be a mare copy of the default one.

**Comment by antoyo** [comment]
I tried once to get the formatting I wanted with rustfmt, but I was unable to because some settings were missing.
Using a different config than rustc will still cause issues to some people because VS Code sometimes ignore the config, so it seems best to use the same config as the Rust project.
It seems we'd only need to add a few lines to `.rustfmt.toml` to use the same config as the Rust project: https://github.com/rust-lang/rust/blob/master/rustfmt.toml#L2-L4

**Comment by tempdragon** [comment]
I once noticed that in some cases, Rustfmt may behave differently on different machines. A friend of mine used VSCode and our rustfmt seemed to behaved differently, causing our code to be reformatted over and over again. Still not sure about why and how.

**Comment by antoyo** [comment]
Apparently, one cause is because formatting a selection of code only sends the code to be formatted to rustfmt, not the filename, so it cannot find the config.

**Comment by tempdragon** [comment]
By the way, have you switched back to vim?

**Comment by antoyo** [comment]
Oh, I never used VS Code. It's some people contributing to cg_gcc via the Rust repo that have this issue.

I've been using neovim (and vim before) for many years.

**Comment by antoyo** [comment]
I formatted the code in #458.

**Comment by tempdragon** [comment]
By the way, is adding a full rustfmt specification useful?
[Customized Conf](https://users.rust-lang.org/t/does-anyone-use-a-customized-configuration-for-rustfmt/66420/7)

**Comment by tgross35** [comment]
You probably want to use the same file as upstream https://github.com/rust-lang/rust/blob/6f435eb0eb2926cdb6640b3382b9e3e21ef05f07/rustfmt.toml, the `ignore` section isn't needed.

Fyi, if these wind up being large changes it's often a good idea to crosscheck. Two people run the same rustfmt commands then `git ls-files -s . | git hash-object --stdin` to make sure their hashes line up.

Adding the hash of the formatting commit to `.git-blame-ignore-revs` gets the noise out of blame views (automatic on GH, need to pass `--ignore-revs-file` via CLI)

**Comment by antoyo** [comment]
Completed by #469.
