### ISSUE TITLE
Support `f16` and `f128`

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rustc_codegen_gcc#461]
As of https://github.com/rust-lang/rust/pull/121728, the backends now have stubs for `f16` and `f128`: https://github.com/rust-lang/rust/blob/6cbf0926d54c80ea6d15df333be9281f65bbeb36/compiler/rustc_codegen_gcc/src/type_.rs#L123-L137.

~~It will be a while before these codepaths can even be exercised since the frontend isn't hooked up yet,~~ (frontend is done now) but at some point this should be changed to either gracefully fail or do the right thing.

**Comment by g4titanx** [comment]
hello @tgross35 can I work on this?

**Comment by tgross35** [comment]
Hey @zedar I saw you did https://github.com/rust-lang/gcc/pull/47 and https://github.com/rust-lang/gccjit.rs/pull/33 for this. Is anything else needed in the GCC backend, or do the `unimplemented!`s at https://github.com/rust-lang/rustc_codegen_gcc/blob/a63b83eb4e46433216dac0558b978619c6746ea8/src/type_.rs#L123-L137 just need to be updated?

**Comment by tgross35** [comment]
Oh I see they were done in https://github.com/antoyo/rustc_codegen_gcc/pull/17, awesome!

I don't have any need for it, just been chasing down the `f16_f128` `FIXMEs` and `unimplemented!`s.

**Comment by tgross35** [comment]
(chances are you know this already, but Miri is using https://github.com/josh-project/josh for supposedly easier syncs, I think Clippy is looking to switch to it too)

**Comment by tgross35** [comment]
I think this has been synced in by now right? A simple example seems to work https://godbolt.org/z/GqWvrza5e.

Many thanks for making this happen!
