### ISSUE TITLE
Rework the option of the build system

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#478]
Currently, the way of building rustc_codegen_gcc without building the sysroot is:
```
./y.sh test --build-only
```

It would be better if `./y.sh build` would do this, so `--build-only` will not be an option for the command `test` anymore.

I see two options here:

 * Add a `--sysroot` flag to `./y.sh build` that will build the sysroot only when this flag is specified.
 * ~Do `./y.sh build --build-only` to not build the sysroot.~

**Comment by mubarak23** [comment]
can you further explain the two options

**Comment by antoyo** [comment]
We decided to go with the first option, so the work to be done would be to not always build the sysroot in the build system when providing the `build` command, but only build it when the `--sysroot` flag is provided.

**Comment by mubarak23** [comment]
this mean building it this way 

`cargo build --sysroot`

**Comment by antoyo** [comment]
No, with the [build system](https://github.com/rust-lang/rustc_codegen_gcc/tree/master/build_system) that we made for rustc_codegen_gcc which is called from [`y.sh`](https://github.com/rust-lang/rustc_codegen_gcc/blob/master/y.sh), so the command would be:
```
./y.sh build --sysroot
```

**Comment by mubarak23** [comment]
interesting, where do i need to make this changes to reflect what are trying to achieve i.e y.sh or Cargo.toml ?

**Comment by antoyo** [comment]
In the [build system](https://github.com/rust-lang/rustc_codegen_gcc/tree/master/build_system), more precisely, you will need to add a new argument [here](https://github.com/rust-lang/rustc_codegen_gcc/blob/master/build_system/src/build.rs#L9-L44) and only build the sysroot when this new argument (flag) is provided by the user.

**Comment by mubarak23** [comment]
now i understand, kindly assign this issue to me, i will work on it

**Comment by antoyo** [comment]
Done.
