### ISSUE TITLE
Run the error UI tests in a new CI job

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#495]
Since some of them has an ICE: https://github.com/rust-lang/rustc_codegen_gcc/issues/296

We currently remove the tests that emits an error in the frontend [here](https://github.com/rust-lang/rustc_codegen_gcc/blob/master/build_system/src/test.rs#L837-L842).
I would like to have a new test that will run those tests (and only these tests with errors) in `failures.yml`.

**Comment by mubarak23** [comment]
@antoyo can you further explain this, i will like to handle it

**Comment by lordshashank** [comment]
@antoyo what do you want to be done here, currently failing rust test suits are ran through ```--test-failing-rustc```  [here](https://github.com/antoyo/rustc_codegen_gcc/blob/d7c8e0fb434144b441e48f79eb2d728b1eab298a/.github/workflows/failures.yml#L99), do you want ui tests to have separate run command like `--test-failing-ui-tests`, and run it under separate name in failures.yaml or something else?

**Comment by antoyo** [comment]
I edit the description to explain more.

**Comment by lordshashank** [comment]
Got it, can work this out now, thanks

**Comment by antoyo** [comment]
I assigned the issue to you.
