### ISSUE TITLE
Mentions in a few places about the possibility for people to not implement the GCC codegen part of their PR

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#503]
* [ ] In the ping message.
 * [ ] Comments at the top of some files.
 * [ ] In the readme.
 * [ ] In the rustc dev guide.

**Comment by Gerson2102** [comment]
Hello @antoyo. I would like to take this one, can you give me more context?

**Comment by antoyo** [comment]
I'm not sure if we actually want this.

@GuillaumeGomez: When we have the GCC codegen distributed in `rustup`, do you think it will be a bad idea to tell people to not implement new features?
Perhaps we could allow it if the tests still pass?

**Comment by antoyo** [comment]
Since we'll soon have rustup distribution (famous last words), we believe it won't be viable if people can break the GCC codegen any day, so let's not do this.
