### ISSUE TITLE
The CI doesn't test with the latest GCC anymore

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#506]
Presumably because of this change: https://github.com/antoyo/rustc_codegen_gcc/pull/18.

Make sure at least one CI will use the latest GCC.

**Comment by GuillaumeGomez** [comment]
I can confirm that it is still testing with the last version. For example in `ci.yml` we have:

```yaml
echo 'gcc-path = "/usr/lib/"' > config.toml
```

Only `stdarch` is using downloaded gccjit library.
