### ISSUE TITLE
Clean up the "Env vars" section of the Readme

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#522]
The [env var](https://github.com/rust-lang/rustc_codegen_gcc?tab=readme-ov-file#env-vars) section mentions some environment variables that do not exist like `CG_GCCJIT_INCR_CACHE_DISABLED` and does not mention variables that exist like `CG_GCCJIT_DUMP_ALL_MODULES`.

**Comment by antoyo** [comment]
Done.

**Comment by Gerson2102** [comment]
Is there some docs that i can look to see if there is more env vars to include and to see what they are doing to put it in the readme?

**Comment by Gerson2102** [comment]
What about these: `std::env::var("GITHUB_ACTIONS")`, `std::env::var("PATH")`?

**Comment by antoyo** [comment]
Please do not add those in the doc.

**Comment by antoyo** [comment]
Fixed by #523.
