### ISSUE TITLE
Do not allow downloading libgccjit.so on other systems than Linux x86-64 in the build system

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#527]

**Comment by g4titanx** [comment]
hey@antonyo, i would love to work on this
just to be sure, the build system should be in build_system/src/build.rs right?

**Comment by antoyo** [comment]
Yes, that is correct.
I suggest you print something like "Compile libgccjit yourself by setting option XXXX" in the case where it's an unsupported platform.
