### ISSUE TITLE
Add support for SIMD

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#63]
* Requires adding support for machine-specific builtins in libgccjit.

**Comment by bjorn3** [comment]
Mostly implemented by https://github.com/rust-lang/rustc_codegen_gcc/pull/129, https://github.com/rust-lang/rustc_codegen_gcc/pull/150, https://github.com/rust-lang/rustc_codegen_gcc/pull/151 and https://github.com/rust-lang/rustc_codegen_gcc/pull/152.

Are the `simd_*` platform intrinsics used by portable-simd implemented?

**Comment by macpp** [comment]
Could https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html be used for portable-simd? or is there better alternative?

**Comment by antoyo** [comment]
This was completed by #254.
