### ISSUE TITLE
Implement 128-bit integers on 32-bit platforms

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#71]

**Comment by bjorn3** [comment]
You could represent 128bit ints as a pair of 64bit ints and call into compiler-builtins when doing math on them.

https://github.com/rust-lang/compiler-builtins/blob/826d9e9d41dca79c9893118fdbb600fc9a837764/src/int/addsub.rs#L64-L96

https://github.com/rust-lang/compiler-builtins/blob/826d9e9d41dca79c9893118fdbb600fc9a837764/src/int/mul.rs#L130-L136

https://github.com/rust-lang/compiler-builtins/blob/826d9e9d41dca79c9893118fdbb600fc9a837764/src/int/sdiv.rs#L158-L166

https://github.com/rust-lang/compiler-builtins/blob/826d9e9d41dca79c9893118fdbb600fc9a837764/src/int/udiv.rs#L56-L98

Only shifts probably need to be implemented by yourself. At least if the shift amount is exactly 64, as that is used by compiler-builtins to implement extraction of the lower and upper half of the 128bit int.

**Comment by antoyo** [comment]
Yeah, but that won't work on platforms without 64-bit integers.

**Comment by bjorn3** [comment]
It will work if you compile compiler-builtins using cg_gcc as in that case you and not llvm gets to decide the abi for 128bit integers passed to compiler-builtins. In any case the abi of u128 and i128 on i686 when using llvm seems to be equivalent to `struct u128(u32, u32, u32, u32);`. That is it is passed on the stack as a single 128bit value and returned using an out pointer.

As for platforms without 64-bit integers, you can do the same trick to split a 64bit int into two 32bit ints and a 128bit int into four 32bit ints.

**Comment by philberty** [comment]
Have you found issues with gcc with 128bit numbers?

**Comment by antoyo** [comment]
No, the problem is that gcc only have [128-bit integers on some platforms](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60846), so I'll have to use a workaround.

**Comment by philberty** [comment]
Thanks for the reply let me see if I can poke some GCC people for some info on this for us.

**Comment by antoyo** [comment]
By the way, not sure if you will be affected by this, but I've seen some places where [rustc will use non-standard integer sizes, like 96 bits](https://github.com/antoyo/rustc_codegen_gcc/blob/master/src/intrinsic/mod.rs#L291), which is not supported by gcc.

**Comment by philberty** [comment]
Interesting I know we can call some stuff to create interest of whatever size but I haven't tested it for cases like that. That looks as though it is some kind of clever optimization I wonder was that code produced by the LLVM optimizers or was it something rustc is telling the backend to do?

**Comment by antoyo** [comment]
It seems to be related to the Rust ABI that put small aggregate types in integers and [an optimization in the Rust frontend that will use integer comparison instead of memcpy](https://github.com/rust-lang/rust/blob/master/compiler/rustc_codegen_llvm/src/intrinsic.rs#L302-L305).

If you know of a way in gcc to create non-standard integers, I'd like to know.

**Comment by philberty** [comment]
Not sure if this helps but for gccrs when doing code generation we create all the usual primitive types here:

https://github.com/Rust-GCC/gccrs/blob/master/gcc/rust/backend/rust-compile-tyty.h#L119-L141
Also here we create the zero-sized integer for unit-type: https://github.com/Rust-GCC/gccrs/blob/40042ce11fc5d7f62e31be99e82bf6a0db83234a/gcc/rust/rust-gcc.cc#L179

This calls out to our GCC wrapper which abstracts the gcc bits and pieces into a nicer API. So it wraps up this piece of code which allows us to specify the number of bits we want: https://github.com/Rust-GCC/gccrs/blob/40042ce11fc5d7f62e31be99e82bf6a0db83234a/gcc/rust/rust-gcc.cc#L886

Which is defined here: https://github.com/Rust-GCC/gccrs/blob/40042ce11fc5d7f62e31be99e82bf6a0db83234a/gcc/stor-layout.c#L2679

**Comment by bjorn3** [comment]
> It seems to be related to the Rust ABI that put small aggregate types in integers

LLVM will lower i96 to an i64 and an i32 argument when using it as call argument.

See https://github.com/bjorn3/rustc_codegen_cranelift/blob/47e4a62ac50aecc36671c0c2cbfb90d82947c827/src/abi/pass_mode.rs#L41 for the cg_clif implementation of PassMode::Cast which the pass mode that cases these types. I am linking the cg_clif code as cranelift only supports power of two integer sizes just like gcc.

**Comment by antoyo** [comment]
Note to myself: The functions to create arbitrary-precision integers are `make_unsigned_type` and `make_signed_type` in gcc.

**Comment by bjorn3** [comment]
Compiler-builtins is already included by the linker logic in cg_ssa. You will need to manually lower unsupported 128bit operations to a call to the right compiler-builtins function though. All the relevant functions can be found in https://github.com/rust-lang/compiler-builtins/tree/master/src/int The logic in cg_clif to call them can be found in https://github.com/bjorn3/rustc_codegen_cranelift/blob/3aae6fb4942d53105f0a699b8fbc07e8dd0aa9c9/src/codegen_i128.rs

**Comment by antoyo** [comment]
Are you sure it's always linked? It seems to me that it's linked by libcore, so using `#[no_core]` gives a linker error like:
```
undefined reference to `__rust_u128_add'
```

**Comment by bjorn3** [comment]
`#![no_core]` is already pretty much unusable for end users. You need to define a lot of lang items to do even basic things. If you want to test it, you should probably not do so in mini_core_hello_world.rs, but instead in std_example.rs.

**Comment by antoyo** [comment]
Fixed by #103.
