### ISSUE TITLE
Segfault when calling Take<Take<Repeat<T>>>::count for certain T

### ISSUE THREAD

**Issue by autumnontape** [rust-lang/rustc_codegen_gcc#74]
The following function segfaults when compiled at opt-level 2 or 3:

```rust
fn segfaults() -> usize {
    core::iter::repeat(()).take(1).take(1).count()
}
```

[The Compiler Explorer output is here.](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,selection:(endColumn:1,endLineNumber:4,positionColumn:1,positionLineNumber:4,selectionStartColumn:1,selectionStartLineNumber:4,startColumn:1,startLineNumber:4),source:'pub+fn+segfaults()+-%3E+usize+%7B%0A++++core::iter::repeat(()).take(1).take(1).count()%0A%7D%0A'),l:'5',n:'0',o:'Rust+source+%231',t:'0')),k:44.90145672664954,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:rustccggcc-master,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,libs:!(),options:'-C+opt-level%3D2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'rustccggcc-master+(Rust,+Editor+%231,+Compiler+%231)',t:'0')),header:(),k:50.26748439078569,l:'4',m:68.69281045751634,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compiler:1,editor:1,fontScale:10,fontUsePx:'0',wrap:'1'),l:'5',n:'0',o:'Output+of+rustccggcc-master+(Compiler+%231)',t:'0')),header:(),l:'4',m:31.30718954248366,n:'0',o:'',s:0,t:'0')),k:55.09854327335048,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4) You can see it produces this very strange line of assembly at the beginning of the function:

```asm
mov     rdx, QWORD PTR ds:0
```

GDB confirms that this is where the segfault occurs.

**Comment by Commeownist** [comment]
I doubt it's about the iter, I think it's about trying to work with a zero sized type (`()`). Support for zero-sized types is very rudimentary at the moment, so expect all sorts of weird behavior when doing things on ZSTs :cry:

**Comment by Commeownist** [comment]
Oh no, that reproduces even with integer types
```rust
fn segfaults() -> usize {
    core::iter::repeat(42).take(1).take(1).count()
}
```

**Comment by autumnontape** [comment]
On the other hand, it produces the expected (non-segfaulting) code when I give it `[0u128; 5000]` instead of `()` or `42i32`.

**Comment by antoyo** [comment]
That seems fixed, now. Maybe thanks to #104.
Can you confirm it is indeed fixed?

**Comment by autumnontape** [comment]
Yes, the snippet I included in the issue description compiles with the latest commit, and the real-world project it was minimized from compiles and passes tests now.
