### ISSUE TITLE
Packed struct

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustc_codegen_gcc#85]

**Comment by bjorn3** [comment]
I think this is already supported. For

```rust
#[repr(packed)]
pub struct Foo(u8, u64, u64);

pub fn foo(v: Foo) -> Foo {
    v
}

//#[repr(packed)]
pub struct Bar(u8, u64, u64);

pub fn bar(v: Bar) -> Bar {
    v
}
```

the only difference between cg_llvm and cg_gcc seems to be different register selection choices, different instruction ordering and gcc using a potentially more efficient instruction for loading a single byte.

https://rust.godbolt.org/z/xdfKxo3v1

**Comment by antoyo** [comment]
Are you sure that if you have such a struct in memory, it will have the correct size?

I thought it's not supported because I don't set the `__packed__ ` attribute.

**Comment by bjorn3** [comment]
I checked that statics work correctly: https://rust.godbolt.org/z/W9j1Y3j7M

Locals however don't work correctly:

```rust
#[repr(packed)]
pub struct Foo(u8, u64, u64);

pub fn foo(mut v: Foo) -> Foo {
    v.0 += 1;
    v.1 += 2; // cg_gcc uses offset 8 here while cg_llvm uses offset 1
    v
}

//#[repr(packed)]
pub struct Bar(u8, u64, u64);

pub fn bar(mut v: Bar) -> Bar {
    v.0 += 1;
    v.1 += 2;
    v
}
```

https://rust.godbolt.org/z/abEnddxbj

**Comment by bjorn3** [comment]
Fixed by https://github.com/rust-lang/rustc_codegen_gcc/pull/148, right?
