### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by QMHTMY** [rust-lang/rustc_codegen_gcc#99]
why not use libgccaot as its name?

**Comment by bjorn3** [comment]
I think libgccjit is called as such because it was meant for JIT purposes and just so happens to support AOT compilation now.

**Comment by antoyo** [comment]
Yeah, the author of libgccjit told me the other day that he was playing with JIT in gcc at the time and named it that way, but then added support for AOT.

**Comment by QMHTMY** [comment]
Thanks!
